import Header from './header/header';
import FullVideo from './fullVideo/fullVideo';
import Footer from './footer/footer';
import Track from './track/track';
import SocialMedia from './socialMedia/socialMedia';
import Fullscreen from './fullscreen/fullscreen';
import Carousel from './carousel/carousel';
import LocaleSwitcher from './localeSwitcher/localeSwitcher';
import IconCard from './iconCard/iconCard';
import Album from './album/album';
export { Header, FullVideo, Footer, Track, SocialMedia, Fullscreen, Carousel, LocaleSwitcher, IconCard, Album };
